#!/usr/bin/env bash

# Script that installs Nginx server and redirects /redirect_me
redirect = "\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}\n"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
sudo service nginx restart
