#!/usr/bin/env bash
# custom 404 error page

redirct="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"
file="/etc/nginx/sites-available/default"
error="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $redirct" "$file"

echo "Ceci n'est pas une page" > "/usr/share/nginx/html/404error.html"
sed -i "37i\ $error" "$file"
service nginx restart
