#!/usr/bin/env bash
#print number from 1 to 20 with a given condition
i=1
while ((i <= 20));
do
    case $i in
        4)
        echo "4"
        echo "bad luck from China"
        ;;
        9)
        echo "9"
        echo "bad luck from Japan"
        ;;
        17)
        echo "17"
        echo "bad luck from Italy"
        ;;
        *)
        echo "$i"
        ;;
    esac
    ((i++))
done