#!/usr/bin/env bash
#print hours and mins
hour=0
while ((hour <= 12));
do
    echo "Hour: $hour"

    min=1
    while ((min <= 59));
    do
        echo "$min"
        ((min++))
    done
    ((hour++))
done
